# Generated by Django 3.2.7 on 2021-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('taste', models.CharField(max_length=200)),
                ('ingredient', models.CharField(max_length=200)),
                ('img_url', models.DateField()),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedFood',
            fields=[
                ('selected_food_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selected_food',
                'managed': False,
            },
        ),
    ]
