# Generated by Django 3.2.7 on 2021-10-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='selectedfood',
            options={},
        ),
    ]
