insert into member values (1, 'nick', 'aa@bb.com','1234','','만두','간장');
insert into food values (1, '소막창구이','회식, 술이땡김, 고소한맛','소, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (2, '돼지막창구이','회식, 술이땡김, 고소한맛','돼지, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (3, '소곱창구이','회식, 술이땡김, 고소한맛','소, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (4, '돼지곱창구이','회식, 술이땡김, 고소한맛','돼지, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (5, '돼지 부속','회식, 술이땡김, 고소한맛','돼지, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (6, '삼겹살','회식, 술이땡김, 고소한맛','돼지','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (7, '우삼겹','회식, 술이땡김, 고소한맛','소','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (8, '생선구이','바삭함, 짭짤한맛','생선','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (9, '소대창구이','회식, 술이땡김, 고소한맛','소, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (10, '돼지대창구이','회식, 술이땡김, 고소한맛','돼지, 내장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (11, '짚불삼겹살구이','회식, 술이땡김','돼지','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (12, '돼지갈비구이','회식, 술이땡김, 짭짤한맛','돼지','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (13, '국화빵','단맛, 추운날','팥, 빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (14, '누가','단맛, 바삭함','견과류, 과자','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (15, '계란빵','단맛, 추운날','계란, 빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (16, '케이크','단맛, 부드러움, 기념일/생일, 즐거움','우유, 빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (17, '철판 아이스크림','단맛, 더운날, 차가움','우유','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (18, '붕어빵','단맛, 추운날','팥','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (19, '머핀','단맛, 우울함','빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (20, '도넛','단맛, 바삭함, 바쁨','빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (21, '호떡','단맛, 추운날','설탕시럽','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (22, '초코케이크','단맛, 부드러움, 우울함, 데이트','초콜릿, 우유, 빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (23, '술빵','새콤, 부드러움','빵, 술','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (24, '크로넛','단맛, 바삭함, 즐거움, 우울함, 데이트','빵, 설탕시럽','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (25, '씨앗호떡','단맛, 추운날, 즐거움','견과류, 설탕시럽','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (26, '스콘','단맛, 바삭함','빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (27, '팥빙수','단맛, 차가움, 더운날','팥','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (28, '카스테라','단맛, 부드러움, 우울함','빵, 계란','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (29, '크레페','단맛, 즐거움, 데이트','우유, 설탕시럽, 과일','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (30, '와플','단맛, 바삭함, 즐거움','설탕시럽, 빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (31, '고로케','바삭함, 바쁨','튀김','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (32, '불닭 볶음면','매운맛, 화남','볶음면, 고추장, 닭','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (33, '짜짜로니','짭짤한맛','볶음면, 춘장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (34, '진짬뽕','얼큰한맛','국물면, 해물','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (35, '진진짜라','짭짤한맛, 매운맛','볶음면, 춘장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (36, '신라면볶음면','짭짤한맛, 매운맛','볶음면','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (37, '오징어짬뽕','추운날, 술이땡김, 얼큰한맛','국물면, 해물','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (38, '진짜장','짭짤한맛','볶음면, 춘장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (39, '열라면','매운맛, 얼큰한맛, 화남, 술이땡김','국물면','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (40, '스낵면','짭짤한맛','국물면','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (41, '염라대왕라면','매운맛, 화남','국물면','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (42, '육회비빔라면','짭짤한맛, 고소한맛','볶음면, 소','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (43, '엽기 떡볶이','매운맛, 화남, 우울함','떡, 고추장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (44, '로제 떡볶이','매운맛, 느끼한맛','떡, 로제, 고추장','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (45, '토스트','바쁨','빵','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (46, '김밥','바쁨','밥, 김','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');
insert into food values (47, '땡초 김밥','간편함, 매운맛','밥, 고추','https://www.youtube.com/watch?v=TAVE8IHAnHc&t=58s');